Bug 414971: Mingw build error: `PR_ROTATE_RIGHT32' was not declared in this scope. r=wtc, sr=pavlov, a=mtschrep
When using macros from prbit.h, don't expect others to include it for you.